apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: '2017-09-29T15:09:35Z'
  name: elasticsearch
  namespace: test-b2share
  resourceVersion: '130161424'
  selfLink: /oapi/v1/namespaces/test-b2share/buildconfigs/elasticsearch
  uid: 343f890c-a528-11e7-870a-02163e00d164
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elasticsearch:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM elasticsearch:2.2
      EXPOSE 9200 9300
      RUN cd /usr/share/elasticsearch && \
        yes | ./bin/plugin install mapper-attachments
      CMD ["elasticsearch"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'elasticsearch:2'
    type: Docker
  triggers: []
status:
  lastVersion: 2
